### ISSUE TITLE
State Usage

### ISSUE THREAD

**Issue by zanethomas** [ChrisFlick/React-Reversi#21]
It appears that state is being maintained in Game and passed around as props. Why?

**Comment by actocchi** [comment]
we havent updated the state yet, this is just a component we have borrowed and are working on. Im about to start going through today and updating and uniforming things.

**Comment by zanethomas** [comment]
As I've mentioned to others it is a really good idea to 1. design the wireframe, 2. design the api, and 3. design and code the data store

Meanwhile I see code is being written. Doing things out of order will only cause more work and bugs later,
